modLoader = "javafml"
loaderVersion = "[35,)"
issueTrackerURL = "${github_repo}/issues"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${display_name}"
authors = "${authors}"
description = '''
${mod_description}
'''
logoFile = "icon.png"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"
